export const navLinks = [
  { title: 'Home', url: 'hero' },
  { title: 'Services', url: 'services' },
  { title: 'Skills', url: 'skills' },
  { title: 'Experience', url: 'experience' },
  { title: 'Portfolios', url: 'portfolios' },
  { title: 'Contact me', url: 'contact' },
]

export const technologies = [
  { title: 'Nuxt 4', icon: 'cib:nuxt-js' },
  { title: 'Vue 3', icon: 'cib:vue-js' },
  { title: 'React', icon: 'cib:react' },
  { title: 'Next', icon: 'cib:next-js' },
  { title: 'Python', icon: 'cib:python' },
  { title: 'Django', icon: 'cib:django' },
  { title: 'JavaScript', icon: 'cib:javascript' },
  { title: 'TypeScript', icon: 'cib:typescript' },
  { title: 'Tailwind', icon: 'mdi:tailwind' },
  { title: 'Sass', icon: 'cib:sass' },
  { title: 'HTML5', icon: 'cib:html5' },
  { title: 'CSS3', icon: 'cib:css3' },
]

export const socialLinks = [
  { icon: 'uil:linkedin-alt', url: 'https://www.linkedin.com/in/kovenko' },
  { icon: 'uil:github-alt', url: 'https://github.com/kowenjko' },
]

export const services = [
  {
    title: 'Frontend Web Development',
    icon: 'uil-layer-group',
    description:
      'Building modern web applications with Vue 3 / Nuxt 3, API integration, performance optimization, and responsive design.',
  },
  {
    title: 'E-commerce Development',
    icon: 'streamline-ultimate:e-commerce-shopping-bag',
    description:
      'Developing and maintaining online stores on Shopify and Shopware, customizing functionality, and integrating payment systems.',
  },
  {
    title: 'UI/UX Implementation',
    icon: 'vaadin:palete',
    description:
      'Translating design mockups (Figma → Vue/React) into clean code, creating intuitive user interfaces with Tailwind, Vuetify, Material UI.',
  },
  {
    title: 'Project Collaboration & Support',
    icon: 'fa7-regular:handshake-simple',
    description:
      'Contributing to team projects with Git, Jira, Trello, Docker. Providing ongoing support and improving existing solutions.',
  },
]

export const workProjects = [
  {
    title: 'StoreInUa online store',
    urlGit: null,
    url: 'https://storeinua.com',
    keywords: ['Nuxt-3', 'I18n', 'Pinia', 'Vuelidate'],
    category: 'Online Shop',
    description:
      'StoreInUa is a Ukrainian online store selling electronics and household appliances (including Apple products, smartphones, and laptops), offering low prices, official warranties, and fast delivery in Kyiv and throughout Ukraine.',
    imageUrl: '/webp/tehko.webp',
  },
  {
    title: 'Automatic processing of price lists',
    urlGit: null,
    url: null,
    keywords: ['Vue', 'Vuetify', 'I18n', 'Pinia', 'Axios'],
    category: 'Online service',
    description:
      'PM-Tehko is a service for automatic price and stock updates. It combines supplier price lists, competitor data, and content databases into a single Master Price List. Through its API, the service integrates with accounting systems and online stores, simplifying price management and increasing product competitiveness.',
    imageUrl: '/webp/pm-tehko.webp',
  },
  {
    title: 'Бідняжка Тур-клуб',
    urlGit: null,
    url: null,
    keywords: ['Nuxt-3', 'Sass', 'I18n', 'Pinia'],
    category: 'Travel agency',
    description: 'Travel - within Ukraine and abroad, with the option of online booking of transport and hotels.',
    imageUrl: '/webp/bidnyagka.webp',
  },
  {
    title: 'Jounce',
    urlGit: null,
    url: 'https://app.jounce.ai/',
    keywords: ['Vue', 'OpenAI', 'Tailwind', 'Firebase'],
    category: 'AI marketing hub',
    description: 'AI copywriting, artwork, and chat for marketing teams',
    imageUrl: '/webp/jounce-2.webp',
  },
  {
    title: 'Jounce',
    urlGit: null,
    url: null,
    keywords: ['Vue', 'Vite', 'Tailwind', 'Firebase'],
    category: 'E-Mail System',
    description: 'Newsletter System with Email and Flow builder.',
    imageUrl: '/webp/jounce.webp',
  },
  {
    title: 'NewPet',
    urlGit: null,
    url: 'https://pfotenkompass.fressnapf.de/',
    keywords: ['Nuxt', 'Vuetify'],
    category: 'Pet shelter service',
    description: 'Developed the frontend based on the design, connecting to the backend CRUD, JWT authorization.',
    imageUrl: '/webp/newpet.webp',
  },
  {
    title: 'Bitburger',
    urlGit: null,
    url: null,
    keywords: ['Shopware', 'Vue'],
    category: 'Online-Shop',
    description: 'Made design changes, developed functionality.',
    imageUrl: '/webp/pitburger.webp',
  },
  {
    title: 'Mylo',
    urlGit: null,
    url: 'https://mylo.de/pages/suewag-ebike-abo',
    keywords: ['Shopify'],
    category: 'Online-Shop',
    description: 'Creation of individual sections by design',
    imageUrl: '/webp/mylo.webp',
  },
  {
    title: 'Planted',
    urlGit: null,
    url: 'https://uk.shop.eatplanted.com/',
    keywords: ['Shopify'],
    category: 'Online-Shop',
    description: 'Made changes to the frontend design.',
    imageUrl: '/webp/planted.webp',
  },
  {
    title: 'Purenature',
    urlGit: null,
    url: 'https://www.purenature-shop.de/',
    keywords: ['Shopify'],
    category: 'Online-Shop',
    description: 'Made changes to the frontend design.',
    imageUrl: '/webp/purenature.webp',
  },
]

export const testProjects = [
  {
    title: 'Nuxt 4 Calendar',
    urlGit: 'https://github.com/Kowenjko/nuxt4-calendar',
    url: 'https://nuxt4-calendar.vercel.app',
    keywords: ['Nuxt 4', 'Drizzle', 'Neon database', 'Tailwindcss'],
    category: 'Calendar',
    description: 'Test program for Nuxt 4 for creating events.',
    imageUrl: '/webp/calendar.png',
  },
  {
    title: 'Nuxt 4 Auth',
    urlGit: 'https://github.com/Kowenjko/nuxt-4-auth',
    url: null,
    keywords: ['Nuxt 4', 'Drizzle', 'Nuxt/ui', 'Nuxt-auth'],
    category: 'Auth',
    description: 'Authorization using Nuxt 3 and drizzle.',
    imageUrl: '/webp/nuxt-a-auth.png',
  },
  {
    title: 'Nuxt Whatsapp Clone',
    urlGit: 'https://github.com/Kowenjko/nuxt-whatsapp-clone',
    url: 'https://nuxt-whatsapp-clone.vercel.app',
    keywords: ['Nuxt 3', 'Tailwind', 'Convex', 'Clerk', 'Zegocloud', 'Emoji', 'Pinia', 'OpenAI', 'Radix'],
    category: 'Chat',
    description: 'The messenger clone uses the following tools: convex, zegocloud, clerk, openai, emoji, shadcn.',
    imageUrl: '/webp/whatsapp.png',
  },
  {
    title: 'Nuxt Auth MongoDB',
    urlGit: 'https://github.com/Kowenjko/nuxt-auth-mongo',
    url: 'https://nuxt-auth-mongo.vercel.app',
    keywords: ['Nuxt 3', 'Tailwind', 'Motion', 'Resend', 'MongoDB', 'Mailtrap', 'Pinia'],
    category: 'Auth',
    description: 'Authorization using Nuxt 3 and mongoDB with the option of confirmation via email by entering a code.',
    imageUrl: '/webp/auth-mongo.png',
  },
  {
    title: 'Zoom Clone',
    urlGit: 'https://github.com/Kowenjko/nuxt-zoom-clone',
    url: null,
    keywords: ['Nuxt 3', 'Tailwind', 'Shadcn', 'Clerk', 'Stream-IO'],
    category: 'Chat',
    description: 'A primitive copy of a meeting on Zoom with video and chat functionality.',
    imageUrl: '/webp/zoom.png',
  },
  {
    title: 'Nuxt MongoDB Trello',
    urlGit: 'https://github.com/Kowenjko/nuxt-mongodb-trello',
    url: null,
    keywords: ['Nuxt 3', 'Vuedraggable', 'MongoDB', 'Stripe', 'Next-Auth'],
    category: 'Info',
    description: 'Minimal copy of Trello is used MongoDB.',
    imageUrl: '/webp/mongodb-trello.png',
  },
  {
    title: 'Nuxt Trello',
    urlGit: 'https://github.com/Kowenjko/nuxt-dashboard-trello',
    url: 'https://nuxt-dashboard-trello.vercel.app',
    keywords: ['Nuxt 3', 'Pinia', 'Tailwind', 'Shadcn', 'Clerk'],
    category: 'Info',
    description: 'Minimal copy of Trello is used localeStorage.',
    imageUrl: '/webp/trello.png',
  },
  {
    title: 'Jotion',
    urlGit: 'https://github.com/Kowenjko/nuxt-notion-clone',
    url: null,
    keywords: ['Nuxt 3', 'Appwrite', 'Pinia', 'Tailwind', 'Shadcn', 'Clerk'],
    category: 'Documents',
    description: 'Your Ideas, Documents, & Plans. Unified.',
    imageUrl: '/webp/notion.png',
  },
  {
    title: 'Chat Appwrite',
    urlGit: 'https://github.com/Kowenjko/vue-realtime-chat-appwrite',
    url: 'https://vue-realtime-chat-appwrite.vercel.app',
    keywords: ['Vue 3', 'Appwrite', 'Pinia'],
    category: 'Chat',
    description: 'Real-time chat made with Vue 3 composition and Appwrite',
    imageUrl: '/webp/chat-appwrite.png',
  },
  {
    title: 'Genius AI',
    urlGit: 'https://github.com/Kowenjko/nuxt-saas-ai',
    url: 'https://nuxt-saas-ai.vercel.app/',
    keywords: ['Nuxt 3', 'Clerk', 'Stripe', 'Tailwind', 'OpenAI', 'Radix', 'Pinia'],
    category: 'AI',
    description:
      'AI chat and generation of images, videos, music, and code, as well as subscription registration via Stripe.',
    imageUrl: '/webp/genius.png',
  },
  {
    title: 'Estate',
    urlGit: 'https://github.com/Kowenjko/mevn-estate',
    url: null,
    keywords: ['Vue', 'Mongodb', 'Node', 'Tailwind', 'Firebase'],
    category: 'Info',
    description: 'Modern real estate marketplace from scratch with jwt authentication and toolkit ',
    imageUrl: '/webp/mevn-estate.png',
  },
  {
    title: 'Insove',
    urlGit: 'https://github.com/Kowenjko/vue-insore',
    url: null,
    keywords: ['Vue 3', 'Pinia', 'Swiper', 'Tailwind'],
    category: 'Info',
    description: 'One-page doctor service page.',
    imageUrl: '/webp/insove.png',
  },
  {
    title: 'Todo',
    urlGit: 'https://github.com/Kowenjko/todo-list-vue.git',
    url: null,
    keywords: ['Vue 3 composition'],
    category: 'Todo list',
    description: 'Demonstration site of the capabilities of Vue 3 composition.',
    imageUrl: '/webp/todo-vue.webp',
  },
  {
    title: 'Game Marine Battle',
    urlGit: 'https://github.com/Kowenjko/See_batle_v2.git',
    url: null,
    keywords: ['HTML', 'CSS', 'JavaScript'],
    category: 'Game',
    description:
      'The game is written on JS, the placement of ships can be automatic or manually. Rules are standard. Wins someone who will find all ships.',
    imageUrl: '/webp/mb.webp',
  },
  {
    title: 'Movie Viewing',
    urlGit: 'https://github.com/Kowenjko/Kursova_2_JS_Kowenjko.git',
    url: null,
    keywords: ['HTML', 'CSS', 'JavaScript'],
    category: 'Video',
    description:
      'The demonstration site is written on a clean JS without libraries, a minimum of HTML. An animation is present. Source News API.',
    imageUrl: '/webp/movie_js.webp',
  },
  {
    title: 'Electro Shop',
    urlGit: 'https://github.com/Kowenjko/Kursova_JS_Kowenjko.git',
    url: null,
    keywords: ['Django', 'Python', 'PostgreSQL'],
    category: 'Shop',
    description: 'The demo site of the store is written in Django, the PostgeSQL database is used.',
    imageUrl: '/webp/django.webp',
  },
  {
    title: 'World News',
    urlGit: 'https://github.com/Kowenjko/Kursova_JS_Kowenjko.git',
    url: null,
    keywords: ['HTML', 'CSS', 'JavaScript'],
    category: 'News',
    description:
      'The demonstration site is written on a clean JS without libraries, a minimum of HTML. An animation is present. Source News API.',
    imageUrl: '/webp/news.webp',
  },
  {
    title: 'React-Bootstrap',
    urlGit: 'https://github.com/Kowenjko/React_Bootstrap.git',
    url: null,
    keywords: ['React', 'Bootstrap'],
    category: 'Info',
    description:
      'In this project, the main components of REACT-BOOTSTRAP are used. To demonstrate the theme `History of Windows`.',
    imageUrl: '/webp/bootstrap_react.webp',
  },
  {
    title: 'Contact List',
    urlGit: 'https://github.com/Kowenjko/React_Homework_1_Kowenjko.git',
    url: null,
    keywords: ['React', 'Redux', 'Bootstrap', 'FireBase'],
    category: 'List',
    description:
      'Demonstration site with contacts written on REACT - Redux + React - Bootstrap + React - Fontawesome. The list is written and read from FireBase.',
    imageUrl: '/webp/List.webp',
  },
  {
    title: 'Material-UI',
    urlGit: 'https://github.com/Kowenjko/React_Material_UI.git',
    url: null,
    keywords: ['React', 'Material-UI'],
    category: 'Info',
    description: 'The demonstration site on React where Material-UI is used.',
    imageUrl: '/webp/Material_ui.webp',
  },
  {
    title: 'Yourcar',
    urlGit: 'https://github.com/Kowenjko/React_Yourcar.git',
    url: null,
    keywords: ['React', 'Styled-Components', 'Tailwind'],
    category: 'Info',
    description: 'The demonstration site is written on React where Styled-Components are used, Tailwind CSS.',
    imageUrl: '/webp/car.webp',
  },
  {
    title: 'Internet-shop',
    urlGit: 'https://github.com/Kowenjko/React_Yourcar.git',
    url: null,
    keywords: ['React', 'Redux'],
    category: 'Shop',
    description:
      'The demonstration site of the online store of computer technology with the ability to add or remove goods from the basket. Written on React, Redux, Middleware.',
    imageUrl: '/webp/Shop.webp',
  },
  {
    title: 'Movie React',
    urlGit: 'https://github.com/Kowenjko/Movie_React.git',
    url: null,
    keywords: ['React', 'Styled-Components'],
    category: 'Video',
    description:
      'Demonstration site on React + Hooks + Styled-Components. Outputs information about movies. TMDB API source.',
    imageUrl: '/webp/Movie_React.webp',
  },
]
